In [1]:
import numpy as np
import pandas as pd

In [2]:
dataframe = pd.read_csv("../../data/Life_Expectancy_Data.csv")

In [3]:
dataframe.head()

,Country,Year,Status,Life expectancy,Adult Mortality,infant deaths,Alcohol,percentage expenditure,Hepatitis B,Measles,...,Polio,Total expenditure,Diphtheria,HIV/AIDS,GDP,Population,thinness 1-19 years,thinness 5-9 years,Income composition of resources,Schooling
0,Afghanistan,2015,Developing,65.0,263.0,62,0.01,71.279624,65.0,1154,...,6.0,8.16,65.0,0.1,584.259210,33736494.0,17.2,17.3,0.479,10.1
1,Afghanistan,2014,Developing,59.9,271.0,64,0.01,73.523582,62.0,492,...,58.0,8.18,62.0,0.1,612.696514,327582.0,17.5,17.5,0.476,10.0
2,Afghanistan,2013,Developing,59.9,268.0,66,0.01,73.219243,64.0,430,...,62.0,8.13,64.0,0.1,631.744976,31731688.0,17.7,17.7,0.470,9.9
3,Afghanistan,2012,Developing,59.5,272.0,69,0.01,78.184215,67.0,2787,...,67.0,8.52,67.0,0.1,669.959000,3696958.0,17.9,18.0,0.463,9.8
4,Afghanistan,2011,Developing,59.2,275.0,71,0.01,7.097109,68.0,3013,...,68.0,7.87,68.0,0.1,63.537231,2978599.0,18.2,18.2,0.454,9.5

In [4]:
dataframe.dtypes

Country                             object
Year                                 int64
Status                              object
Life expectancy                    float64
Adult Mortality                    float64
infant deaths                        int64
Alcohol                            float64
percentage expenditure             float64
Hepatitis B                        float64
Measles                              int64
 BMI                               float64
under-five deaths                    int64
Polio                              float64
Total expenditure                  float64
Diphtheria                         float64
 HIV/AIDS                          float64
GDP                                float64
Population                         float64
 thinness  1-19 years              float64
 thinness 5-9 years                float64
Income composition of resources    float64
Schooling                          float64
dtype: object

#Timeline

In [5]:
dataframe["Year"].unique()

array([2015, 2014, 2013, 2012, 2011, 2010, 2009, 2008, 2007, 2006, 2005,
       2004, 2003, 2002, 2001, 2000], dtype=int64)

In [6]:
#keep only the last year
dataframe=dataframe[dataframe["Year"]==2015]

In [12]:
df1=dataframe[["Country","Year","Status","Life expectancy "]]

In [13]:
df1

                                 Country  Year      Status  Life expectancy
0                            Afghanistan  2015  Developing              65.0
16                               Albania  2015  Developing              77.8
32                               Algeria  2015  Developing              75.6
48                                Angola  2015  Developing              52.4
64                   Antigua and Barbuda  2015  Developing              76.4
...                                  ...   ...         ...               ...
2858  Venezuela (Bolivarian Republic of)  2015  Developing              74.1
2874                            Viet Nam  2015  Developing              76.0
2890                               Yemen  2015  Developing              65.7
2906                              Zambia  2015  Developing              61.8
2922                            Zimbabwe  2015  Developing              67.0

[183 rows x 4 columns]

In [14]:
df.groupby(['Status'])['value_col'].mean()

ValueError: Wrong number of items passed 2, placement implies 1